# EDITING VALUES HERE WILL NOT CHANGE THE CONFIG.
# EDIT CONFIG.YML INSTEAD.

# Set where the game will kick players out to and also where to go to when running /skywars lobby.
# Set this position with /setlobby in your SkyWars lobby.
LobbyLocation:

# The amount of players required in a game before it will start.
MinimumPlayers: 12
# The maximum amount of players allowed in a game.
# There MUST be as many spawn points on a map as half this amount.
# Due to how matchmaking works it's recommended to make sure this is the same as the minimum.
# It must also be an even number.
MaximumPlayers: 12


# The multiplier. Higher multiplier = more loot.
DefaultIslandMultiplier: 1

# The default levels of each type of loot found on starting islands.
# Set to 0 to disable that type of loot.
DefaultIslandSwordLevel: 1
DefaultIslandBowLevel: 1
DefaultIslandPearlLevel: 1
DefaultIslandProjectileLevel: 1

DefaultMidMultiplier: 1
# The default levels of each type of loot found on mid islands.
DefaultMidSwordLevel: 3
DefaultMidBowLevel: 3
DefaultMidPearlLevel: 3
DefaultMidProjectileLevel: 3

# Each type of loot has 4 levels.
# In custom games, the host can choose which loot levels of each type of loot they want.
# You can set whatever loot you like in any of the categories.
SwordLevels:
  1:
    # The chance that an item from this level will show up in a chest.
    chance: 50
    # How many times the game should see if an item from here should be added to a chest.
    # For example, if rolls are 2 and chance is 100, 2 items from this level will always show up in a chest.
    rolls: 2
    # The items in this level.
    # Each item has an equal chance of showing up in a chest.
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
      - ==: org.bukkit.inventory.ItemStack
        type: STONE_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            FIRE_ASPECT: 1
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_SWORD
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            FIRE_ASPECT: 1
            DAMAGE_ALL: 2

BowLevels:
  1:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 8
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_KNOCKBACK: 1
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 16
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 32
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_KNOCKBACK: 2
            ARROW_INFINITE: 1
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 64

PearlLevels:
  1:
    chance: 10
    rolls: 1
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 1
  2:
    chance: 20
    rolls: 1
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 1
  3:
    chance: 20
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 1
  4:
    chance: 50
    rolls: 5
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 2

ProjectileLevels:
  1:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 12
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 12
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 5