# Below are options for loot levels and other options. You can see detailed explanations in
# configtemplate.yml.

LobbyLocation:

MinimumPlayers: 12
MaximumPlayers: 12

DefaultIslandMultiplier: 1
DefaultIslandSwordLevel: LEVEL_1
DefaultIslandBowLevel: LEVEL_1
DefaultIslandPearlLevel: LEVEL_1
DefaultIslandProjectileLevel: LEVEL_1
DefaultIslandArmorLevel: LEVEL_1
DefaultIslandMiscLevel: LEVEL_1

DefaultMidMultiplier: 1
DefaultMidSwordLevel: LEVEL_3
DefaultMidBowLevel: LEVEL_3
DefaultMidPearlLevel: LEVEL_3
DefaultMidProjectileLevel: LEVEL_3
DefaultMidArmorLevel: LEVEL_3
DefaultMidMiscLevel: LEVEL_3

SwordLevels:
  1:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
      - ==: org.bukkit.inventory.ItemStack
        type: STONE_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            FIRE_ASPECT: 1
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_SWORD
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            FIRE_ASPECT: 1
            DAMAGE_ALL: 2

BowLevels:
  1:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 8
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_KNOCKBACK: 1
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 16
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 32
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_KNOCKBACK: 2
            ARROW_INFINITE: 1
      - ==: org.bukkit.inventory.ItemStack
        type: ARROW
        amount: 64

PearlLevels:
  1:
    chance: 5
    rolls: 1
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 1
  2:
    chance: 10
    rolls: 1
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 1
  3:
    chance: 10
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 1
  4:
    chance: 50
    rolls: 5
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: ENDER_PEARL
        amount: 2

ProjectileLevels:
  1:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 8
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 12
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 12
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: SNOWBALL
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        type: EGG
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        type: FISHING_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 5


ArmorLevels:
  1:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: LEATHER_HELMET
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_HELMET
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_BOOTS
      - ==: org.bukkit.inventory.ItemStack
        type: LEATHER_CHESTPLATE
  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_HELMET
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_CHESTPLATE
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_LEGGINGS
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_BOOTS
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_HELMET
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_BOOTS
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_HELMET
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_BOOTS
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 5


MiscLevels:
  1:
    chance: 100
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: STONE_PICKAXE
      - ==: org.bukkit.inventory.ItemStack
        type: OAK_PLANKS
        amount: 16
      - ==: org.bukkit.inventory.ItemStack
        type: STONE
        amount: 16

  2:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: IRON_PICKAXE
      - ==: org.bukkit.inventory.ItemStack
        type: OAK_PLANKS
        amount: 32
      - ==: org.bukkit.inventory.ItemStack
        type: STONE
        amount: 32
  3:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_PICKAXE
      - ==: org.bukkit.inventory.ItemStack
        type: OAK_LOG
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        type: STONE
        amount: 64
  4:
    chance: 50
    rolls: 2
    items:
      - ==: org.bukkit.inventory.ItemStack
        type: DIAMOND_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 5
      - ==: org.bukkit.inventory.ItemStack
        type: OAK_LOG
        amount: 64
      - ==: org.bukkit.inventory.ItemStack
        type: STONE
        amount: 64